Create and export `CountdownBar` tokens
selsa-inube/inubekit-foundations pull request #52
Opened 2024-03-05 23:28 UTC by JanuarAsprilla

tokens are created and exported in `CountdownBar`

2024-03-05 23:38 UTC, cmarin001 requested changes

2024-03-05 23:38 UTC, cmarin001 commented on src/components/countdownbar.ts
> +const countdown_bar = {
I would suggest reviewing the naming convention for this JSON, as it may lead to potential issues as well as integrate with main branch in order to avoid merge issues

2024-03-05 23:39 UTC, JanuarAsprilla commented on src/components/countdownbar.ts
> +const countdown_bar = {
solved

2024-03-06 14:15 UTC, wfercanas requested changes

2024-03-06 14:15 UTC, wfercanas commented on src/components/countdownbar.ts
> +const countdownbar = {
Create the variable as it is in the token table: `countdown-bar`.

2024-03-06 14:29 UTC, JanuarAsprilla commented on src/components/countdownbar.ts
> +const countdownbar = {
solved

2024-03-06 15:05 UTC, wfercanas approved these changes

2024-03-06 15:06 UTC, merged